print('Enter 4 numbers:')
a = input()
b = input()
c = input()
d = input()
sum_first = float(a) + float(b)
sum_second = float(c) + float(d)
result = round((sum_first/sum_second), 2)
print('Result: ', result)